/**
 * Sabha events — the list of actual gatherings.
 *
 * Everything used to be derived from "the upcoming Friday", so the day was a
 * constant in the code. This replaces that with a list of real events, each with
 * its own date, times, venue and status.
 *
 * Documents are `events/{YYYY-MM-DD}`, keyed by their own date. Deliberate:
 *
 *  - Attendance is stored under `weeklyAttendance/{eventId}`, and eventId has
 *    always been the gathering's date. Keying events the same way means every
 *    existing attendance record still lines up, so this needs no migration.
 *  - It makes "is there a sabha on the 14th?" a document read rather than a
 *    query.
 *
 * The cost is that two gatherings cannot share a date. That is a real
 * limitation, and the right time to lift it is when locations arrive (roadmap
 * phase 2), because per-location events need a compound key anyway.
 */

import * as admin from 'firebase-admin';
import { zonedDateKey, addDaysToDateKey } from './time';
import {
    RecurrenceRule, EventException, normaliseException, upcomingOccurrences,
    effectiveEventFor,
} from './recurrence';
import { parseExceptionId, LOOKAHEAD_NEEDS_SLACK } from './locations';

export const EVENTS_COLLECTION = 'events';

/**
 * Where the seed marker lives.
 *
 * `system/*` is denied to every client in firestore.rules, so only a Cloud
 * Function can write this. That matters: if a manager could clear it, they could
 * make the seeder run again and resurrect a date they had just deleted.
 */
export const SEED_MARKER_DOC = 'system/eventGenerator';

/**
 * How far ahead `findCurrentEvent` will look for the next gathering.
 *
 * A DATE bound, not a document-count bound. `.limit(20)` meant a long run of
 * skipped documents ahead of a scheduled event returned null while a scheduled
 * event existed — closing the service on the 21st document rather than on
 * anything meaningful.
 */
const LOOKAHEAD_DAYS = 90;

/** An event id is the gathering's own date. */
const DATE_KEY_PATTERN = /^\d{4}-\d{2}-\d{2}$/;

/**
 * Which gathering a ride belongs to, taken from the ride itself.
 *
 * Returns null when the ride cannot say — callers then fall back to today's date
 * *in the congregation's zone*, never to a UTC one. That distinction is the whole
 * point of this function: a Friday-night drop-off in Boston completes after
 * midnight UTC, so a UTC date files it under Saturday, splitting one gathering's
 * numbers across two documents and leaving the Friday one unfindable.
 *
 * `eventId` is preferred over `eventDate` because the server writes it from
 * `system/rideContext` when the ride is assigned, whereas `eventDate` comes from
 * the requesting browser. Both are the gathering's date, so they agree whenever
 * the device clock did.
 */
export function eventKeyFromRide(ride: unknown): string | null {
    const r = ride as { eventId?: unknown; eventDate?: unknown } | null | undefined;
    if (!r) return null;

    for (const candidate of [r.eventId, r.eventDate]) {
        if (typeof candidate === 'string' && DATE_KEY_PATTERN.test(candidate)) {
            return candidate;
        }
    }
    return null;
}

export type EventStatus = 'scheduled' | 'cancelled';

export interface SabhaEvent {
    /** "YYYY-MM-DD" — also the document id. */
    date: string;
    /** "HH:MM" in Sabha local time. */
    startTime: string;
    endTime: string;
    /** Overrides settings/main for this one gathering. Null means use the default. */
    venue: { lat: number; lng: number; address: string } | null;
    status: EventStatus;
    agenda: string;
    /** True when generated by the weekly template rather than created by hand. */
    autoCreated?: boolean;
}

/**
 * The gathering the app should currently be working towards.
 *
 * Today's event if there is one, otherwise the soonest scheduled one after
 * today. Cancelled events are skipped, so cancelling next Friday correctly rolls
 * everything on to the one after.
 *
 * Today's event stays current for the WHOLE day, including after it has ended —
 * drop-off rides are still running then, and rolling the eventId over at the end
 * of sabha would move the attendance key out from under them.
 *
 * Returns null when nothing is scheduled. Callers must treat that as "closed"
 * rather than inventing a date: quietly falling back to a guessed Friday is how
 * the old code hid the fact that nobody had scheduled anything.
 */
export async function findCurrentEvent(
    db: admin.firestore.Firestore,
    now: Date,
    timeZone: string,
    rule: RecurrenceRule | null = null,
): Promise<SabhaEvent | null> {
    return (await resolveCurrentEvent(db, now, timeZone, rule)).event;
}

/**
 * How many candidate evenings to look past when every hall on one is closed.
 *
 * Only reachable with `locationIds` given, and only when a manager has cancelled each
 * hall of an evening one at a time instead of cancelling the date. Eight is about two
 * months of Fridays.
 *
 * ponytail: a fixed ceiling, not a walk to the horizon. Cancel every hall on eight
 * consecutive sabha dates and the ninth is missed, reported as closed. Raise the
 * number if that ever stops being absurd; the real upgrade path is a per-hall
 * recurrence rule, at which point this whole function resolves per hall from the start.
 */
const CLOSED_EVENING_LOOKAHEAD = 8;

export interface CurrentEventResolution {
    /** The evening being worked towards, resolved at the DATE level. Null = closed. */
    event: SabhaEvent | null;

    /**
     * That evening's per-hall exception documents, keyed by location id.
     *
     * Handed back rather than left to a second query, because this function already
     * reads every document in the range — the hall slice is free here and a round trip
     * anywhere else. Empty when no hall has one, which is the ordinary case.
     */
    hallExceptions: Map<string, EventException>;
}

/**
 * `findCurrentEvent`, plus the per-hall exceptions for the evening it picked.
 *
 * Split out so `updateRideTypeContext` can resolve each hall's own times without a
 * second read of the same documents, while the six existing callers keep the narrow
 * signature they had.
 *
 * @param locationIds when given, AN EVENING ONLY COUNTS IF AT LEAST ONE OF THESE HALLS
 *   IS OPEN ON IT. Pass null (the default) for the date-level answer alone. Without
 *   this, a manager who cancelled both halls of an evening separately — rather than
 *   cancelling the date — would leave the app announcing a sabha that no hall is
 *   holding: reminders sent, window opened, and every rider told their hall is closed.
 * @param pendingCancellation an event id to resolve AS IF it were already cancelled.
 *   `deleteSabhaEvent` needs the answer before its batch commits, and the document it
 *   is cancelling is still there to be read. Passing it here rather than searching
 *   again afterwards is what makes a per-hall cancellation work: the same evening may
 *   still be on for another hall, so "the next gathering" is not a question about the
 *   date at all, and the old find-then-look-after-it approach could not express that.
 */
export async function resolveCurrentEvent(
    db: admin.firestore.Firestore,
    now: Date,
    timeZone: string,
    rule: RecurrenceRule | null = null,
    locationIds: readonly string[] | null = null,
    pendingCancellation: string | null = null,
): Promise<CurrentEventResolution> {
    const closed: CurrentEventResolution = { event: null, hallExceptions: new Map() };
    const today = zonedDateKey(now, timeZone);
    const horizon = addDaysToDateKey(today, LOOKAHEAD_DAYS);

    try {
        // THE SAME SINGLE QUERY AS BEFORE.
        //
        // Worth stating plainly, because moving from "documents are gatherings" to
        // "a rule, with documents as its exceptions" sounds like it should cost
        // more reads and does not. It reads the same date range; those documents
        // are now exceptions rather than the schedule itself, and the schedule is
        // computed. This runs every minute, so the cost mattered.
        //
        // Both bounds on documentId(), so no composite index is needed. Adding a
        // status equality would force one for no gain — `normaliseException` and
        // `effectiveEvent` decide what each document means anyway.
        const snapshot = await db.collection(EVENTS_COLLECTION)
            .where(admin.firestore.FieldPath.documentId(), '>=', today)
            // A DAY OF SLACK, because a hall's document id is `${date}__${hall}` and
            // '2026-11-05__somerville' <= '2026-11-05' is false. Without it, a second
            // hall's gathering on the exact horizon day is invisible. Reading one extra
            // day of exception documents costs nothing; the resolver's own horizon
            // below is unchanged, so no date past it can be returned.
            .where(admin.firestore.FieldPath.documentId(), '<=',
                addDaysToDateKey(horizon, LOOKAHEAD_NEEDS_SLACK))
            .orderBy(admin.firestore.FieldPath.documentId())
            .get();

        // TWO MAPS, because one document id means two different things now. A bare id
        // is the whole evening's exception; a suffixed one speaks for a single hall.
        // Keyed together they would collide in meaning — `upcomingOccurrences` guards
        // itself against a suffixed key, but a hall's cancellation read as the date's
        // would close a sabha the other hall is still holding.
        const exceptions = new Map<string, EventException>();
        const byDateAndHall = new Map<string, Map<string, EventException>>();
        for (const doc of snapshot.docs) {
            const exception = normaliseException(doc.data());
            if (!exception) continue;

            // `parseExceptionId`, not `parseEventId`: a bare document is the WHOLE
            // EVENING'S exception, older than the idea of halls, and `parseEventId`
            // would resolve it to the founding hall — leaving every other hall reading
            // the rule as if nothing had been edited. It also accepts a suffix naming
            // the founding hall, which is a shape exceptions write and data keys never
            // do.
            const parsed = parseExceptionId(doc.id);
            if (!parsed) continue;
            if (parsed.locationId === null) {
                exceptions.set(parsed.dateKey, exception);
                continue;
            }
            const forDate = byDateAndHall.get(parsed.dateKey) ?? new Map();
            forDate.set(parsed.locationId, exception);
            byDateAndHall.set(parsed.dateKey, forDate);
        }

        if (pendingCancellation) {
            // A full EventException, because `effectiveEvent` reads `status` first and
            // short-circuits — but a half-built record here would be a trap for the
            // next person to add a field to that type.
            const cancelled: EventException = {
                kind: 'override', status: 'cancelled',
                startTime: '', endTime: '', venue: null, agenda: '',
            };
            const parsed = parseExceptionId(pendingCancellation);
            if (parsed?.locationId === null) {
                exceptions.set(parsed.dateKey, cancelled);
            } else if (parsed) {
                const forDate = byDateAndHall.get(parsed.dateKey) ?? new Map();
                forDate.set(parsed.locationId, cancelled);
                byDateAndHall.set(parsed.dateKey, forDate);
            }
        }

        // One occurrence is all this needs when no halls were named; the manager's
        // calendar asks the same function for more. Sharing it is what keeps the
        // scheduler and the calendar from disagreeing about what the schedule says.
        const wanted = locationIds ? CLOSED_EVENING_LOOKAHEAD : 1;
        const candidates = upcomingOccurrences(rule, exceptions, today, horizon, wanted);

        const occurrence = locationIds
            ? candidates.find(c => locationIds.some(id => effectiveEventFor(
                c.date, rule, exceptions.get(c.date) ?? null,
                byDateAndHall.get(c.date)?.get(id) ?? null,
            )))
            : candidates[0];
        if (!occurrence) return closed;

        const hallExceptions = byDateAndHall.get(occurrence.date) ?? new Map();
        return { hallExceptions, event: {
            date: occurrence.date,
            startTime: occurrence.startTime,
            endTime: occurrence.endTime,
            venue: occurrence.venue,
            status: 'scheduled',
            agenda: occurrence.agenda,
            // "Not created by hand" now means "came from the rule", which is the
            // same distinction under a different mechanism.
            autoCreated: occurrence.source === 'rule',
        } };
    } catch (error) {
        console.error('[events] Could not read events:', error);
        return closed;
    }
}

/**
 * The seeding machinery that used to live here is gone.
 *
 * `weeklySlotDate` and `seedFirstEventIfNeeded` existed to create ONE gathering
 * on a brand-new project so the service was not closed on day one, plus the
 * `toEvent` reader that turned a document into a gathering. All three assumed
 * documents ARE the schedule.
 *
 * Under the rule model the schedule is `settings/sabhaRecurrence`, and a project
 * with no rule is honestly closed — `calendarStatus: 'no-scheduled-event'` says
 * so on the manager's calendar, next to the control that fixes it. Seeding a
 * gathering nobody asked for, to avoid admitting that, was papering over exactly
 * the thing the manager needs to see.
 *
 * SEED_MARKER_DOC stays. It is no longer a seed marker — it carries
 * `pendingAttendanceDeletes`, drained by the scheduler. Deleting the constant
 * would orphan that queue.
 */
