/**
 * Sabha events — the list of actual gatherings.
 *
 * Everything used to be derived from "the upcoming Friday", so the day was a
 * constant in the code. This replaces that with a list of real events, each with
 * its own date, times, venue and status.
 *
 * Documents are `events/{YYYY-MM-DD}`, keyed by their own date. Deliberate:
 *
 *  - Attendance is stored under `weeklyAttendance/{eventId}`, and eventId has
 *    always been the gathering's date. Keying events the same way means every
 *    existing attendance record still lines up, so this needs no migration.
 *  - It makes "is there a sabha on the 14th?" a document read rather than a
 *    query.
 *
 * The cost is that two gatherings cannot share a date. That is a real
 * limitation, and the right time to lift it is when locations arrive (roadmap
 * phase 2), because per-location events need a compound key anyway.
 */

import * as admin from 'firebase-admin';
import { zonedDateKey, addDaysToDateKey, getZonedParts } from './time';
import {
    DEFAULT_SABHA_START, DEFAULT_SABHA_END, SABHA_DAY, parseTimeToMinutes,
} from './schedule';

export const EVENTS_COLLECTION = 'events';

/** How many weeks ahead the weekly template keeps events populated. */
export const AUTOCREATE_WEEKS_AHEAD = 8;

export type EventStatus = 'scheduled' | 'cancelled';

export interface SabhaEvent {
    /** "YYYY-MM-DD" — also the document id. */
    date: string;
    /** "HH:MM" in Sabha local time. */
    startTime: string;
    endTime: string;
    /** Overrides settings/main for this one gathering. Null means use the default. */
    venue: { lat: number; lng: number; address: string } | null;
    status: EventStatus;
    agenda: string;
    /** True when generated by the weekly template rather than created by hand. */
    autoCreated?: boolean;
}

/** Normalise a Firestore document into a usable event, or null if unusable. */
function toEvent(id: string, data: any): SabhaEvent | null {
    if (!data) return null;

    const startTime = typeof data.startTime === 'string' && parseTimeToMinutes(data.startTime) !== null
        ? data.startTime
        : DEFAULT_SABHA_START;
    const endTime = typeof data.endTime === 'string' && parseTimeToMinutes(data.endTime) !== null
        ? data.endTime
        : DEFAULT_SABHA_END;

    const venue = data.venue
        && typeof data.venue.lat === 'number'
        && typeof data.venue.lng === 'number'
        ? {
            lat: data.venue.lat,
            lng: data.venue.lng,
            address: typeof data.venue.address === 'string' ? data.venue.address : '',
        }
        : null;

    return {
        date: typeof data.date === 'string' ? data.date : id,
        startTime,
        endTime,
        venue,
        status: data.status === 'cancelled' ? 'cancelled' : 'scheduled',
        agenda: typeof data.agenda === 'string' ? data.agenda : '',
        autoCreated: data.autoCreated === true,
    };
}

/**
 * The gathering the app should currently be working towards.
 *
 * Today's event if there is one, otherwise the soonest scheduled one after
 * today. Cancelled events are skipped, so cancelling next Friday correctly rolls
 * everything on to the one after.
 *
 * Today's event stays current for the WHOLE day, including after it has ended —
 * drop-off rides are still running then, and rolling the eventId over at the end
 * of sabha would move the attendance key out from under them.
 *
 * Returns null when nothing is scheduled. Callers must treat that as "closed"
 * rather than inventing a date: quietly falling back to a guessed Friday is how
 * the old code hid the fact that nobody had scheduled anything.
 */
export async function findCurrentEvent(
    db: admin.firestore.Firestore,
    now: Date,
    timeZone: string,
): Promise<SabhaEvent | null> {
    const today = zonedDateKey(now, timeZone);

    try {
        const snapshot = await db.collection(EVENTS_COLLECTION)
            .where(admin.firestore.FieldPath.documentId(), '>=', today)
            .orderBy(admin.firestore.FieldPath.documentId())
            .limit(20)
            .get();

        for (const doc of snapshot.docs) {
            const event = toEvent(doc.id, doc.data());
            if (event && event.status === 'scheduled') return event;
        }

        return null;
    } catch (error) {
        console.error('[events] Could not read events:', error);
        return null;
    }
}

/**
 * The date of the Nth upcoming occurrence of the weekly slot.
 *
 * Offset 0 is the next one, counting today if today is the day.
 */
export function weeklySlotDate(
    now: Date,
    timeZone: string,
    dayOfWeek: number,
    weeksAhead: number,
): string {
    const { dayOfWeek: todayDow } = getZonedParts(now, timeZone);
    const daysUntil = (dayOfWeek - todayDow + 7) % 7;
    return addDaysToDateKey(zonedDateKey(now, timeZone), daysUntil + weeksAhead * 7);
}

/**
 * Keep the calendar populated.
 *
 * With a list of events instead of a hardcoded Friday, an empty calendar means
 * no rides at all — so forgetting to add next week would silently close the
 * service on a congregation that has no way to tell why. This fills the next
 * AUTOCREATE_WEEKS_AHEAD occurrences of the weekly slot from the default times.
 *
 * Only ever CREATES missing documents. It never touches an existing one, so a
 * manager's edited time, moved venue or cancellation is never overwritten.
 */
export async function ensureUpcomingEvents(
    db: admin.firestore.Firestore,
    now: Date,
    timeZone: string,
    defaults: { startTime: string; endTime: string },
    dayOfWeek: number = SABHA_DAY,
): Promise<string[]> {
    const created: string[] = [];

    for (let week = 0; week < AUTOCREATE_WEEKS_AHEAD; week++) {
        const date = weeklySlotDate(now, timeZone, dayOfWeek, week);
        const ref = db.collection(EVENTS_COLLECTION).doc(date);

        try {
            const existing = await ref.get();
            if (existing.exists) continue;

            await ref.create({
                date,
                startTime: defaults.startTime,
                endTime: defaults.endTime,
                venue: null,
                status: 'scheduled',
                agenda: '',
                autoCreated: true,
                createdAt: new Date().toISOString(),
            });
            created.push(date);
        } catch (error: any) {
            // ALREADY_EXISTS means a concurrent run won the race, which is fine.
            if (error?.code !== 6) {
                console.error(`[events] Could not create ${date}:`, error);
            }
        }
    }

    return created;
}
